---
Channels:
  chofu-fm: http://hdv3.nkansai.tv/chofu
  fmsagami: mms://122.29.249.8/fmsagami_simul
ExtendSeconds: 15
FfmpegPath: /usr/bin/ffmpeg
Mp4tagsPath: /usr/bin/mp4tags
MplayerPath: /usr/bin/mplayer
RadiruConfig: http://www3.nhk.or.jp/netradio/app/config_pc.xml
RtmpDumpPath: /usr/bin/rtmpdump
SavePath: .
SwfVfy: http://www3.nhk.or.jp/netradio/files/swf/rtmpe_ver2015.swf

