---
ExtendSeconds: 15
RadiruConfig: http://www3.nhk.or.jp/netradio/app/config_pc.xml
RtmpDumpPath: C:/Program Files (x86)/RTMPDump/rtmpdump.exe
SavePath: .
SwfVfy: http://www3.nhk.or.jp/netradio/files/swf/rtmpe_ver2015.swf
